name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - run: npm install && npm run build
    
      # 部署到 GitHub Pages
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: main
#           FOLDER: docs/.vuepress/dist
