name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
    - run: npm install && npm run build
    
      # 部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          repository-name: David-XIa001/JSON-internationalization
          BRANCH: pages
          FOLDER: dist
          CLEAN: true

    #   # 部署到 GitHub Pages
    # steps:
    # - name: Deploy
    #   #  进入生成的文件夹
    #   - run: cd docs/.vuepress/dist
    #   - run: git init && git add . && git commit -m "部署" && git push -f `https://David-XIa001:${ACCESS_TOKEN}@github.com/David-XIa001/JSON-internationalization.git` master:gh-pages
    #   - run: cd ../ && rm -rf docs/.vuepress/dist